<h1><?php echo $titulo; ?></h1>
<h3><?php if (!empty($mensagem)): echo $mensagem; endif; ?></h3>

<form action="index.php?page=salvarUsuario" method="POST">
    <label for="email"/>
    <input id="email" name="email" type="text" value="<?php if (!empty($email)): echo $email; endif; ?>"/>
    <br />

    <label for="senha"/>
    <input id="senha" name="senha" type="password"/>
    <br />

    <label for="confirmarSenha"/>
    <input id="confirmarSenha" name="confirmarSenha" type="password"/>
    <br />
    <br />

    <input type="submit" value="Salvar"/><a href="index.php?page=listarUsuarios">Cancelar</a>
</form>