<html>
    <head>
        <link rel="stylesheet" type="text/css" href="css/estilos.css">
    </head>
    <body>
        <div id="geral">
            <div id="cabecalho">
                Cabecalho
            </div>

            <div id="barrasuperior">
                Barra superior
                <div id="entrar">
                    <a href="index.php?page=editarUsuario&id=<?php echo $login->getId(); ?>"><?php echo $login->getEmail(); ?></a>
                    <a href="index.php?page=logout">Logout</a>
                </div>
            </div>

            <div id="centro">
                <div id="barratitulo">
                    <?php echo $titulo; ?>
                </div>

                <?php if (!empty($mensagem)): ?>
                    <div id="barramensagem">
                        <?php echo $mensagem; ?>
                    </div>
                <?php endif; ?>

                <form action="index.php?page=atualizarUsuario" method="POST">
                    <div id="corpo">
                        <label for="email">Email:</label>
                        <input id="email" name="email" type="text" value="<?php echo $usuario->getEmail() ?>"/>
                        <br />

                        <label for="senha">Senha:</label>
                        <input id="senha" name="senha" type="password"/>
                        <br />

                        <label for="confirmarSenha">Confirmar a senha:</label>
                        <input id="confirmarSenha" name="confirmarSenha" type="password"/>

                        <input name="id" type="hidden" type="text" value="<?php echo $usuario->getId() ?>"/>
                    </div>

                    <div id="barraacoes">
                        <input type="submit" value="Salvar"/><a href="index.php?page=listarUsuarios">Cancelar</a>
                    </div>
                </form>
            </div>

            <div id="rodape">
                Rodape
            </div>
        </div>
    </div>
</body>
</html>