<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="css/estilos.css">
    </head>
    <body>
        <div id="geral">
            <h1><?php echo $titulo; ?></h1>
            <h3><?php if (!empty($mensagem)): echo $mensagem; endif; ?></h3>

            <form action="index.php?page=atualizarUsuario" method="POST">
                <div id="formulario">
                    <label for="email">Email:</label>
                    <input id="email" name="email" type="text" value="<?php echo $usuario->getEmail() ?>"/>
                    <br />

                    <label for="senha">Senha:</label>
                    <input id="senha" name="senha" type="password"/>
                    <br />

                    <label for="confirmarSenha">Confirmar a senha:</label>
                    <input id="confirmarSenha" name="confirmarSenha" type="password"/>
                </div>

                <input name="id" type="hidden" type="text" value="<?php echo $usuario->getId() ?>"/>
                <div id="botoes">
                    <input type="submit" value="Salvar"/><a href="index.php?page=listarUsuarios">Cancelar</a>
                </div>
            </form>
        </div>
    </body>
</html>