<html>
    <head>
        <link rel="stylesheet" type="text/css" href="css/estilos.css">
        <script src="js/scripts.js"></script>
    </head>
    <body>
        <div id="geral">
            <div id="cabecalho">
                Cabecalho
            </div>

            <div id="barrasuperior">
                Barra superior
                <div id="entrar">
                    <a href="index.php?page=editarUsuario&id=<?php echo $login->getId(); ?>"><?php echo $login->getEmail(); ?></a>
                    <a href="index.php?page=logout">Logout</a>
                </div>
            </div>

            <div id="centro">
                <div id="barratitulo">
                    <?php echo $titulo; ?>
                </div>

                <?php if (!empty($mensagem)): ?>
                    <div id="barramensagem">
                        <?php echo $mensagem; ?>
                    </div>
                <?php endif; ?>

                <?php if (!empty($usuarios)): ?>
                    <div id="corpo">
                        <table>
                            <tr>
                                <th>Email</th>
                                <th>Senha</th>
                                <th>Acoes</th>
                            </tr>
                            <?php foreach ($usuarios as $usuario): ?>
                                <tr>
                                    <td>
                                        <a href="index.php?page=editarUsuario&id=<?php echo $usuario->getId(); ?>"><?php echo $usuario->getEmail(); ?></a>
                                    </td>
                                    <td><?php echo $usuario->getSenha(); ?></td>
                                    <td class="acoes">
                                        <a href="index.php?page=editarUsuario&id=<?php echo $usuario->getId(); ?>">Editar</a>
                                        <a href="index.php?page=deletarUsuario&id=<?php echo $usuario->getId(); ?>" onclick="return popupConfirmacao('Tens certesa?')">Deletar</a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </table>
                    </div>
                <?php endif; ?>

                <form action="index.php?page=criarUsuario" method="POST">
                    <div id="barraacoes">
                        <input type="submit" value="Criar"/>
                    </div>
                </form>
            </div>

            <div id="rodape">
                Rodape
            </div>
        </div>
    </body>
</html>