<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="css/estilos.css">
    </head>
    <body>
        <div id="geral">
            <h1><?php echo $titulo; ?></h1>
            <h3><?php if (!empty($mensagem)): echo $mensagem; endif; ?></h3>

            <form action="index.php?page=login" method="POST">
                <div id="formulario">
                    <label for="email" class="rotulo">Email:</label>
                    <input id="email" name="email" type="text"/>
                    <br />

                    <label for="senha" class="rotulo">Senha:</label>
                    <input id="senha" name="senha" type="password"/>
                </div>
                <div id="botoes">
                    <input type="submit" value="Login"/>
                </div>
            </form>
        </div>
    </body>
</html>