<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title></title>
        <link rel="stylesheet" type="text/css" href="css/estilos.css">
    </head>
    <body>
        <div id="geral">
            <div id="cabecalho">
                Cabecalho
            </div>

            <div id="barrasuperior">
                Barra superior
                <div id="entrar">
                </div>
            </div>

            <div id="centro">
                <div id="barratitulo">
                    <?php echo $titulo; ?>
                </div>

                <?php if (!empty($mensagem)): ?>
                    <div id="barramensagem">
                         <?php echo $mensagem; ?>
                    </div>
                <?php endif; ?>

                <form action="index.php?page=login" method="POST">
                    <div id="corpo">
                        <label for="email" class="rotulo">Email:</label>
                        <input id="email" name="email" type="text"/>
                        <br />

                        <label for="senha" class="rotulo">Senha:</label>
                        <input id="senha" name="senha" type="password"/>
                    </div>

                    <div id="barraacoes">
                        <input type="submit" value="Login"/>
                    </div>
                </form>
            </div>

            <div id="rodape">
                Rodape
            </div>
        </div>
    </body>
</html>